/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rodolph_abdul.razak_bako;

import java.awt.HeadlessException;
import javax.swing.*;
import java.awt.event.*;
import java.io.*;
import java.util.Set;


/**
 *
 * @author DELL
 */
public class NewJFrame extends javax.swing.JFrame {

    public NewJFrame() {
        initComponents();
        CalculateGPA_Savefile.addActionListener((ActionEvent evt) -> {
            calculateAndSaveGPA();
        });
        
        Clearbtn.addActionListener((ActionEvent evt) -> {
            clearAllFields();
        });
    }
    
    private void calculateAndSaveGPA() {
        try {
            String name = StudentsName.getText().trim();
            String id = StudentID.getText().trim();

            int rowCount = CoursesInfo.getRowCount();
            double totalPoints = 0;
            int totalCredits = 0;
            StringBuilder courseDetails = new StringBuilder();

            for (int i = 0; i < rowCount; i++) {
                Object courseObj = CoursesInfo.getValueAt(i, 0);
                Object creditObj = CoursesInfo.getValueAt(i, 1);
                Object gradeObj = CoursesInfo.getValueAt(i, 2);

                if (courseObj == null || creditObj == null || gradeObj == null) continue;

                String course = courseObj.toString().trim();
                int credit = Integer.parseInt(creditObj.toString().trim());
                String grade = gradeObj.toString().trim().toUpperCase();
                
                if (grade.isEmpty()) {
    throw new IllegalArgumentException("Grade missing in row " + (i + 1));
}

Set<String> validGrades = Set.of("A", "B+", "B", "C+", "C", "D", "E", "F");
if (!validGrades.contains(grade)) {
    throw new IllegalArgumentException("Invalid grade \"" + grade + "\" in row " + (i + 1));
}

double point = switch (grade) {
    case "A" -> 4.0;
    case "B+" -> 3.5;
    case "B" -> 3.0;
    case "C+" -> 2.5;
    case "C" -> 2.0;
    case "D" -> 1.5;
    case "E" -> 1.0;
    case "F" -> 0.0;
    default -> throw new IllegalArgumentException("Unexpected error with grade in row " + (i + 1));
};


                totalPoints += point * credit;
                totalCredits += credit;
                courseDetails.append("- ").append(course)
                        .append(" (").append(credit).append(" hrs): ")
                        .append(grade).append("\n");
            }

            double gpa = totalCredits > 0 ? totalPoints / totalCredits : 0.0;

            if (SaveTo.getSelectedItem().toString().contains("File")) {
                saveToFile(name, id, courseDetails.toString(), gpa);
                JOptionPane.showMessageDialog(this, "GPA: " + String.format("%.2f", gpa) + "\nSaved to file.");
            } else {
                JOptionPane.showMessageDialog(this, "Database under construction.");
            }
        } catch (HeadlessException | IOException | IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void saveToFile(String name, String id, String courseDetails, double gpa) throws IOException {
        try (PrintWriter out = new PrintWriter(new FileWriter("gpa_records.txt", true))) {
            out.println("Name: " + name);
            out.println("ID: " + id);
            out.println("Courses/Credits/Grades:");
            out.print(courseDetails);
            out.println("GPA: " + String.format("%.2f", gpa));
            out.println("--------------------------------------");
        }
    }

    private void clearAllFields() {
        StudentsName.setText("");
        StudentID.setText("");
        Remarks.setText("");
        for (int i = 0; i < CoursesInfo.getRowCount(); i++) {
            for (int j = 0; j < CoursesInfo.getColumnCount(); j++) {
                CoursesInfo.setValueAt(null, i, j);
            }
        }
        SaveTo.setSelectedIndex(0);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SaveTo = new javax.swing.JComboBox<>();
        CalculateGPA_Savefile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Remarks = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        StudentsName = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        StudentID = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        CoursesInfo = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        Clearbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("GPA CALCULATOR");

        SaveTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "File", "Database : Under Construction" }));
        SaveTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveToActionPerformed(evt);
            }
        });

        CalculateGPA_Savefile.setText("Calculate GPA");

        Remarks.setColumns(20);
        Remarks.setRows(5);
        jScrollPane1.setViewportView(Remarks);

        StudentsName.setColumns(20);
        StudentsName.setRows(5);
        jScrollPane2.setViewportView(StudentsName);

        jLabel2.setText("Student's ID");

        StudentID.setColumns(20);
        StudentID.setRows(5);
        jScrollPane3.setViewportView(StudentID);

        jLabel3.setText("Student's Name");

        jLabel4.setText("Courses (Input Them)");

        CoursesInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course", "Credit Hours", "Grade ( A to F )"
            }
        ));
        jScrollPane5.setViewportView(CoursesInfo);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Write your remarks");

        Clearbtn.setText("Clear all fields");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(249, 249, 249))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(CalculateGPA_Savefile)
                                .addGap(337, 337, 337))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(50, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(122, 122, 122))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveTo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Clearbtn)
                        .addGap(15, 15, 15)))
                .addGap(326, 326, 326))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addGap(71, 71, 71)
                .addComponent(Clearbtn)
                .addGap(18, 18, 18)
                .addComponent(SaveTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CalculateGPA_Savefile)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveToActionPerformed
    
    }//GEN-LAST:event_SaveToActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateGPA_Savefile;
    private javax.swing.JButton Clearbtn;
    private javax.swing.JTable CoursesInfo;
    private javax.swing.JTextArea Remarks;
    private javax.swing.JComboBox<String> SaveTo;
    private javax.swing.JTextArea StudentID;
    private javax.swing.JTextArea StudentsName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
