
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.FileWriter;
/**
 *
 * @author Rikkard2099
 */
public class Calculator extends JFrame {

    // UI Components
    JTextField nameField, idField;
    JTable courseTable;
    JComboBox<String> saveBox;
    JButton calcButton;


    /**
     * Creates new form Calculator
     */
    public Calculator() {
        // This part will be done in the JFrame GUI form
        // Example: nameField = new JTextField();
        //          calcButton = new JButton("Calculate GPA");

        // But if coding manually:
        setTitle("GPA Calculator");
        setSize(600, 400);
        setLayout(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        // Text Fields
        nameField = new JTextField();
        nameField.setBounds(100, 20, 150, 25);
        add(new JLabel("Name:")).setBounds(20, 20, 50, 25);
        add(nameField);

        idField = new JTextField();
        idField.setBounds(100, 60, 150, 25);
        add(new JLabel("ID:")).setBounds(20, 60, 50, 25);
        add(idField);

        // Table for Course, Credit, Grade
        String[] columns = {"Course", "Credit Hours", "Grade (A-F)"};
        courseTable = new JTable(new DefaultTableModel(columns, 5));
        JScrollPane scrollPane = new JScrollPane(courseTable);
        scrollPane.setBounds(20, 100, 540, 100);
        add(scrollPane);

        // ComboBox
        saveBox = new JComboBox<>(new String[]{"Save to File", "Save to Database"});
        saveBox.setBounds(20, 220, 150, 25);
        add(saveBox);

        // Button
        calcButton = new JButton("Calculate GPA");
        calcButton.setBounds(200, 220, 150, 25);
        add(calcButton);

        // Action
        calcButton.addActionListener(e -> calculateGPA());

        setVisible(true);
    }

    void calculateGPA() {
        String name = nameField.getText();
        String id = idField.getText();

        double totalPoints = 0;
        double totalCredits = 0;

        // Loop through table rows
        for (int i = 0; i < courseTable.getRowCount(); i++) {
            Object creditObj = courseTable.getValueAt(i, 1);
            Object gradeObj = courseTable.getValueAt(i, 2);

            if (creditObj == null || gradeObj == null) continue;

            double credit = Double.parseDouble(creditObj.toString());
            String grade = gradeObj.toString().toUpperCase();

            double gradePoint = switch (grade) {
                case "A" -> 4.0;
                case "B" -> 3.0;
                case "C" -> 2.0;
                case "D" -> 1.0;
                default -> 0.0;
            };

            totalPoints += gradePoint * credit;
            totalCredits += credit;
        }

        double gpa = totalCredits == 0 ? 0 : totalPoints / totalCredits;

        JOptionPane.showMessageDialog(this, "GPA: " + gpa);

        String saveOption = (String) saveBox.getSelectedItem();
        if (saveOption.equals("Save to File")) {
            try {
                FileWriter writer = new FileWriter("gpa_records.txt", true);
                writer.write("Name: " + name + ", ID: " + id + ", GPA: " + gpa + "\n");
                writer.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error saving file");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Database: Under Construction");
        }
    }

   public static void main(String[] args) {
        new Calculator();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("GPA Calculator");

        jTextField1.setText("Student Name");

        jLabel2.setText("Name:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 222, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
